### ISSUE TITLE
Consider altering current STY/LTY

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfdlm#15]
- Could be average proportion of yield (based on `Yield`).
- Could be based on probability of hitting some fraction of yield from the FMSYref PM.

Challenge with that second option is just needing to make a different kind of PM function that can also take the FMSYref values as input.

Current implementation even makes FMSYref look not so great from a fisheries yield perspective in the rex case study.

**Comment by seananderson** [comment]
Added the second option here: https://github.com/pbs-assess/gfdlm/commit/8fd830eff8723ccadd93ca83cfa9e36b62bde6f5
which, perhaps unsurprisingly, is almost exactly the same as the original LTY and STY.

**Comment by robynforrest** [comment]
Doesn't Option 2 fail if you didn't run the FMSYref pm? 

Currently I think  the plots show yield/MSY (their proxy for MSY)? I think it would be good to maybe have that as a default if there is no target yield, but have the option of inputting the range of years for averaging a target yield?

Or, in my mseR paper, I just made everything completely relative. Each PM was standardized to the maximum (best) performance among MPs.

**Comment by seananderson** [comment]
Wasn't failing for me yesterday... but I've left it and reverted to the usual LTY for now anyways.
