### ISSUE TITLE
Can we make a function factory for biennial surveys MPs?

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfdlm#2]
I assume it would do something like take the data object, set odd or even year survey indexes and biological samples to NA, and then pass the modified object on to the true MP. Probably depends how the MPs are set up to work with NAs.

If this doesn't work that I think we are going to have to copy and modify all MPs that we want to test.

**Comment by cgrandin** [comment]
I think we can, but we will have to run through each MP manually to see if it can handle the NAs. For example, the AvC function takes the mean, removing the NAs so that one's fine
