### ISSUE TITLE
Grabbing the correct index values for plotting

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfdlm#20]
@quang-huynh, I created this function to plot samples from the projected index:
https://github.com/pbs-assess/gfdlm/blob/master/R/figures-index.R

This takes the data from:
`purrr::map(mse@Misc$Data, "Ind")`

Questions:
1. What enables `AddInd` such that it isn't just NAs? I can I add an option to use `Ind` or `AddInd`.
2. Presumably this isn't the correct historical index data if the real data has been added via your SRA function into cpars. Where should I be grabbing that from in the MSE object?

**Comment by quang-huynh** [comment]
For the i-th MP, the real indices are grabbed from `mse@Misc$Data[[i]]@AddInd` which is a concatenated array of both historical and projected indices. By default, the slot is all NA unless historical indices are provided in `OM@cpars$Data@AddInd`.
