### ISSUE TITLE
Fix NAMESPACE to be compatible with new DLMtool/MSEtool

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfdlm#25]
I suspect a bunch of things (e.g., ChkYrs) have been moved from DLMtool to MSEtool in the new packages (now housed at https://github.com/Blue-Matter). 
gfdlm will no longer load

**Comment by robynforrest** [comment]
For now I will put out the gfdlm functions I need in my repo

**Comment by quang-huynh** [comment]
As part of the quillback work, I'm planning to update the package as needed alongside the new packages here: https://github.com/quang-huynh/gfdlm/tree/dev

@robynforrest let me know if you want to coordinate any updates.

**Comment by seananderson** [comment]
That would be awesome. Thanks @quang-huynh. Let me know if anything doesn't make sense. There are a few plotting functions that we never ended up using in there.

**Comment by robynforrest** [comment]
Great, thank you @quang-huynh!

**Comment by seananderson** [comment]
Hmm, good point. gfmse?

**Comment by quang-huynh** [comment]
Could also do gfmpf (MP Framework). The most precise would be gfopenmse.

**Comment by seananderson** [comment]
We had called the MP Framework repo itself gfmp, which would be shorter... but I suppose we could rename that too.

On second thought, there's nothing groundfish-specific about this package. It's mostly a bunch of plotting utilities for openMSE and some utilities for MP and PM creation/modification. Naming things is hard.

**Comment by seananderson** [comment]
- MPutils
- ggmse
- ggMSE
- ggmpf
- ggMPF
- MPF
- mpf

Hmm. I'm leaning towards ggmse or mpf right now.

**Comment by quang-huynh** [comment]
I'd be happy with ggmse!
